from pathlib import Path
import json,re,html

root=Path(__file__).resolve().parents[3]
base=root/'muzei/literatura'
old=(base/'lit-slovo-o-polku-igoreve.html').read_text()
scenes=json.loads((Path(__file__).parent/'scenes.json').read_text())
if isinstance(scenes,dict):scenes=scenes.get('scenes',scenes.get('moments'))
esc=html.escape
hook=(Path(__file__).parent/'hero.txt').read_text().strip()
header=re.search(r'<header class="top">.*?</nav>',old,re.S).group(0)
audio_cfg=re.search(r'<script>window.MUSEUM_AUDIOGUIDE=.*?</script>',old,re.S).group(0)
audio_cfg=audio_cfg.replace("heading:'Плач Ярославны — услышать'","heading:'Услышать, как она ждала'")
audio_cfg=audio_cfg.replace("durationLabel:'около полутора минут'","durationLabel:'1 минута 35 секунд'")
audio_cfg=re.sub(r"lead:'[^']*'", "lead:'Она хочет долететь до мужа и обтереть его раны. Послушай её просьбу к ветру, реке и солнцу.'",audio_cfg)
audio_cfg=audio_cfg.replace("Перевод Василия Жуковского.","По переводу Василия Жуковского.")
audio_cfg=audio_cfg.replace("note:'Озвучено синтезом речи — временно, до записи голосом.'","note:'Синтезированное чтение. Адаптация перевода В. А. Жуковского; древнерусский текст доступен отдельно.'")

css='''
:root{--acc:#c9a84c;--acc-soft:rgba(201,168,76,.16)}
body{font-size:18px}.wrap{max-width:960px}.block{padding:44px 0}p{max-width:66ch}
header.top .b2{opacity:1;color:#c3b69d}header.top .b3{font-size:16px}header.top .b4{font-size:12px;color:#c3b69d}
.hero-scene{height:330px;overflow:hidden;background:#130f0b}.hero-img{width:100%;height:100%;object-fit:cover;object-position:center 48%}
.scene-caption{font-family:Inter,sans-serif;font-size:14px;line-height:1.5;padding:12px 0;color:#c3b69d}
.hero-lead{padding:22px 0 26px}.hero-lead h1{font-size:clamp(32px,5vw,58px);margin:10px 0 15px}.hook{font-size:clamp(20px,2.5vw,25px);line-height:1.45;max-width:780px}
.hero-btns{display:flex;flex-wrap:wrap;gap:10px;margin-top:20px}.btn{min-height:46px;display:inline-flex;align-items:center;text-decoration:none}.who{color:#c3b69d}.date-chip{font-size:13px}
.hero-under .stamp{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.stamp .v{font-size:24px}.stamp .k{font-size:13px}
.moment{border-top:1px solid #4b3c28;padding:34px 0}.moment:first-child{border:0}.moment .n{font:13px Inter,sans-serif;color:#c9a84c;letter-spacing:.1em}.moment h2{font-size:clamp(26px,4vw,40px);margin:9px 0 14px;max-width:800px}.moment .lead{font-size:20px;line-height:1.55;max-width:740px;margin:0 0 15px}
details{border-top:1px solid #4b3c28;margin-top:20px}summary{cursor:pointer;min-height:48px;padding:14px 0;color:#e4c97a;font:16px/1.5 Inter,sans-serif}details p{line-height:1.8;font-size:18px}.source{font:14px/1.6 Inter,sans-serif;color:#c3b69d}
.human-frame{margin:28px 0}.human-frame img{width:100%;height:auto;display:block}.human-frame figcaption{font:14px/1.6 Inter,sans-serif;color:#c3b69d;margin-top:12px}.human-frame.portrait{max-width:440px;margin:28px auto}
.voice-first{background:#18110c;border-top:1px solid #4b3c28}.voice-first .quote{font:clamp(26px,4vw,42px)/1.35 'Playfair Display',Georgia,serif;color:#ead8ac;max-width:800px;margin:20px 0}
.storyline{display:grid;grid-template-columns:repeat(4,1fr);list-style:none;padding:0;gap:0;margin:30px 0}.storyline li{border-top:2px solid #b69143;padding:14px 16px 0 0;font:16px/1.5 Inter,sans-serif}.storyline span{display:block;color:#c3b69d;font-size:14px;margin-top:8px}.storyline-note{font:14px Inter,sans-serif;color:#c3b69d}
.game-hall{background:#17120c;border-top:2px solid #8f6a2a}.game-hall h2{font-size:34px}.game-hall .game{margin:28px 0;padding:24px 0;border-top:1px solid #4b3c28}
.ending{font-size:24px;line-height:1.6;max-width:750px}.source-list{font-size:16px;line-height:1.8}.jump-links{display:flex;flex-wrap:wrap;gap:12px;font:14px Inter,sans-serif;margin:18px 0}.jump-links a{min-height:44px;display:flex;align-items:center}
.btn:focus-visible,button:focus-visible,summary:focus-visible,a:focus-visible{outline:3px solid #f3d989;outline-offset:4px}
.crumbs .here{opacity:1}.tl{font-size:16px}.tl li{margin-bottom:14px}
@media(max-width:640px){body{font-size:17px}.wrap{padding:0 20px}.hero-scene{height:23vh;min-height:165px;max-height:210px}.scene-caption{font-size:13px;padding:8px 0}.hero-lead{padding:14px 0}.hero-lead h1{font-size:32px}.hook{font-size:19px}.who{font-size:13px}.hero-btns{margin-top:14px}.hero-btns .btn{font-size:14px;padding:10px 13px}.block{padding:30px 0}.moment{padding:27px 0}.moment .lead{font-size:18px}.hero-under .stamp{gap:8px}.stamp .v{font-size:20px}.stamp .k{font-size:12px}.storyline{grid-template-columns:1fr 1fr;row-gap:20px}.ending{font-size:21px}header.top .b4{font-size:11px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*{transition:none!important;animation:none!important}}
'''

sections=[]
for i,s in enumerate(scenes):
    paras=''.join('<p>'+esc(p)+'</p>' for p in s['paragraphs'])
    source=s.get('source','https://feb-web.ru/feb/slovo/texts/a50/a50-007-.htm?cmd=p')
    if isinstance(source,list):source=source[0]
    if isinstance(source,str):source=source.split(' ; ')[0]
    if isinstance(source,dict):source=source.get('url','')
    sid=s.get('id','scene-'+str(i+1))
    visual=''
    if i==1:visual='<figure class="human-frame"><img src="media-slovo/hero-battle-1880.jpg" width="1400" height="734" alt="Павшие воины в степи на картине Васнецова" loading="lazy"><figcaption>Виктор Васнецов. «После побоища Игоря Святославича с половцами», 1880. Государственная Третьяковская галерея. Художественный образ, созданный через столетия после похода.</figcaption></figure>'
    if i==2:visual='<figure class="human-frame portrait"><img src="media-slovo/plach-yaroslavny.jpg" width="758" height="962" alt="Ярославна на городской стене, руки прижаты к груди" loading="lazy"><figcaption>Василий Перов. «Плач Ярославны», 1881. Образ героини у художника XIX века.</figcaption></figure>'
    if i==4:visual='<figure class="human-frame"><img src="hero-slovo-1800.jpg" width="1440" height="810" alt="Титульный лист и начало первого издания Слова1800 года" loading="lazy"><figcaption>Первое издание. Москва, Сенатская типография, 1800. Эти печатные страницы появились до пожара1812 года.</figcaption></figure>'
    sections.append(f'<article class="moment" id="{esc(sid)}"><div class="n">{i+1:02d} / Пять историй</div><h2>{esc(s["title"])}</h2><p class="lead">{esc(s["lead"])}</p>{visual}<details><summary>{["Почему он не повернул","Что увидел пленённый князь","Чего она просила","Как удалось уйти","Кто сохранил её голос"][i]}</summary>{paras}<p class="source"><a href="{esc(source)}" target="_blank" rel="noopener">Источник эпизода</a> · {esc(["По сюжету «Слова». Редакционный пересказ.","По Ипатьевской летописи в академическом комментарии.","По плачу Ярославны. Редакционный пересказ.","По сюжету «Слова» и академическому комментарию.","История сохранения текста. Погиб поздний список, не автограф автора."][i])}</p></details></article>')

choice={"mount":"choiceTale","title":"Пока исход неизвестен","steps":[
{"text":"Игорь ещё может повернуть назад. Знамение тревожит дружину, впереди чужая степь. Какой довод для тебя важнее?","choices":[{"label":"Сберечь людей: цена риска слишком высока","tag":"беречь людей"},{"label":"Продолжить: войско готово, отступление перечеркнёт поход","tag":"довести начатое"}]},
{"text":"Позади разгром. Возможность побега связана с помощью Овлура — половца. На чём держится доверие в такой ситуации?","choices":[{"label":"На поступке: он действительно готов помочь","tag":"довериться поступку"},{"label":"Мне нужны доказательства: слишком многое поставлено на карту","tag":"проверить помощь"}]},
{"text":"Князь вернулся, но погибших вернуть нельзя. Что ты прежде всего сохранишь в рассказе об этом походе?","choices":[{"label":"Отвагу и возвращение — людям нужна надежда","tag":"помнить надежду"},{"label":"Потери и ответственность — чтобы помнить цену решения","tag":"помнить цену"}]}],
"weights":{},"reality":{"label":"В истории осталось и то и другое.","text":"Игорь продолжил поход и оказался в плену. Овлур помог ему бежать. В «Слове» радость возвращения соседствует с горем о погибших. Это читательская развилка: твой выбор не меняет исторический исход."}}

quiz={"mount":"quiz","title":"Кого ты запомнил в этой истории?","points":20,"items":[
{"q":"Кто помог Игорю уйти из половецкого плена?","o":["Овлур, половец","Всеволод привёл новое войско","Мусин-Пушкин"],"c":0,"e":"Овлур помог побегу. Мусин-Пушкин связан с другой судьбой — сохранением самого произведения много веков спустя."},
{"q":"Что Ярославна хочет сделать, долетев до мужа?","o":["Вручить ему оружие","Обтереть его кровавые раны","Потребовать нового похода"],"c":1,"e":"Она хочет смочить рукав и обтереть раны мужа. За княжеской историей появляется желание оказаться рядом с любимым."},
{"q":"Что сохранило текст после пожара1812 года?","o":["Спасённый автограф поэта","Только устные рассказы","Печатное издание1800 года и сделанная до пожара копия"],"c":2,"e":"Погиб рукописный сборник. Издание и Екатерининская копия сохранили текст; погибший список не был установленным автографом автора."},
{"q":"Кем был Всеволод для Игоря?","o":["Братом","Сыном","Половецким ханом"],"c":0,"e":"Всеволод — брат Игоря. Летописный рассказ показывает горе пленённого князя, который видит, как брат ещё сражается."},
{"q":"Чем закончился поход1185 года для русского войска?","o":["Победой и взятием столицы","Поражением и пленением князей","Бескровным возвращением"],"c":1,"e":"Поход закончился поражением. Позднейший побег Игоря не отменяет потерь — поэтому возвращение и цена похода остаются рядом."}]}

head=f'''<!doctype html><html lang="ru" data-museum="literatura" data-fabric="manuscript"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Слово о полку Игореве — плен, брат и возвращение домой</title><meta name="description" content="{esc(hook)}"><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="../../assets/fonts.css"><link rel="stylesheet" href="../../assets/museum-literatura.css"><link rel="stylesheet" href="../../assets/museum-theme.css"><style>{css}</style></head><body>'''
body=f'''{header}
<div class="hero-scene"><img class="hero-img" src="media-slovo/hero-battle-1880.jpg" alt="Павшие воины в степи: картина Васнецова После побоища" width="1400" height="734"></div>
<div class="scene-caption"><div class="wrap"><div class="scene-cap">Виктор Васнецов. «После побоища Игоря Святославича с половцами»,1880. Государственная Третьяковская галерея.</div></div></div>
<header class="hero-lead"><div class="wrap"><div class="date-chip">1 января · условный день календаря</div><div class="who">Неизвестный русский поэт · конец XII века</div><h1>Слово о полку Игореве</h1><p class="hook">{esc(hook)}</p><div class="hero-btns"><a class="btn gold" href="#five-stories">Что случилось дальше ↓</a><a class="btn ghost" href="#audioguide">Услышать Ярославну</a></div></div></header>
<div class="hero-under"><div class="wrap"><div class="stamp"><div><div class="v">1185</div><div class="k">поход Игоря</div></div><div><div class="v">Брат</div><div class="k">Всеволод</div></div><div><div class="v">Путивль</div><div class="k">голос Ярославны</div></div><div><div class="v">1800</div><div class="k">первое издание</div></div></div></div></div>
<main>
<section class="block voice-first" id="plach"><div class="wrap"><div class="kicker">Там бьются. Здесь ждут.</div><h2>Она хочет только оказаться рядом</h2><p class="quote">Долететь. Смочить рукав. Обтереть его раны.</p><p>В плаче Ярославны есть это простое желание: добраться до любимого и помочь ему своими руками.</p><div id="audioguide"></div><details><summary>Прочитать слова неизвестного поэта</summary><blockquote>Омочю бебрянъ рукавъ въ Каялѣ рѣцѣ, утру князю кровавыя его раны на жестоцѣмъ его тѣлѣ.</blockquote><p class="source">Древнерусский текст в академической передаче1950 года. Короткие фразы над плеером — редакционный пересказ.</p></details></div></section>
<section class="block" id="five-stories"><div class="wrap">{''.join(sections)}</div></section>
<section class="block" id="story"><div class="wrap"><div class="kicker">Ушёл за славой. Вернулся из плена.</div><h2>Дорога домой не стирает того, что было</h2><ol class="storyline"><li>Поход<span>Игорь ведёт дружину в степь.</span></li><li>Поражение<span>Князья в плену. Часть дружины погибла.</span></li><li>Побег<span>Овлур помогает Игорю уйти.</span></li><li>Домой<span>Возвращение приносит радость. Потери остаются.</span></li></ol><p class="storyline-note">Схема основных событий. Голос Ярославны звучит в поэтическом рассказе, а не в точной хронологии её действий.</p><details><summary>Почему поэт обращается ко всей Русской земле</summary><p>Из истории одного похода вырастает просьба к русским князьям: соединить силы. Автор знает цену отваге. Он знает и то, что одних храбрых людей недостаточно, когда каждый правитель действует сам по себе.</p><p>В этих строках живёт страна, за которую тревожатся: её города, поля, реки и люди. Память о них оказывается больше отдельной княжеской славы.</p></details></div></section>
<section class="block game-hall" id="games"><div class="wrap"><div class="kicker">Твой выбор</div><h2>Ты ещё не знаешь, чем всё кончится</h2><p>Попробуй принять три решения, а потом сопоставь их с историей. Здесь не оценивают твою смелость.</p><div class="game" id="choiceTale"></div><div class="game" id="quiz"></div><p class="source">Баллы — только за пять вопросов о прочитанном, по20. Выбор в истории не оценивается. Повторные ответы не увеличивают счёт.</p></div></section>
<section class="block" id="result"><div class="wrap"><h2>Вернуться. Дождаться. Сохранить.</h2><p class="ending">Князь вернулся. Погибшие — нет. Ярославнин голос остался. А потом нашлись люди, благодаря которым даже пожар не заставил его замолчать.</p><p>Вот что дошло до нас через восемь веков: отвага, боль за близкого, надежда и любовь к Русской земле.</p><div class="card"><div class="gm-bar"><i id="dayBar" style="width:0%"></i></div><div id="dayTxt">0 /100</div></div><div class="diploma" id="dipl" style="display:none"><b>Внимательный читатель «Слова»</b><p>Пять верных ответов о людях и судьбе произведения.</p><span id="dpts">100</span></div></div></section>
<section class="block" id="istochniki"><div class="wrap"><details><summary>Источники и что именно они подтверждают</summary><ul class="source-list"><li><a href="https://feb-web.ru/feb/slovo/texts/a50/a50-007-.htm?cmd=p">Академический текст «Слова»</a>: решение Игоря, плач, побег.</li><li><a href="https://feb-web.ru/feb/slovo/texts/a50/a50-375-.htm?cmd=p">Академические комментарии и летописные свидетельства</a>: Игорь и Всеволод, помощь Овлура.</li><li><a href="https://kp.rusneb.ru/item/material/iroicheskaya-pesn-o-pohode-na-polovcov-udelnago-knyazya-novagoroda-severskago-igorya-svyatoslavicha">Первое издание в НЭБ</a>: Москва,1800.</li><li><a href="https://feb-web.ru/feb/slovbul/bul-abc/bul/bul-0982.htm?cmd=p&amp;istext=1">Екатерининская копия и гибель списка</a>.</li></ul><p>Повествование соединяет сюжет произведения с обозначенными летописными свидетельствами. Погибшая рукопись была поздним списком. Имя автора неизвестно. Изображения художников XIX века передают их прочтение истории.</p></details></div></section>
<section class="block" id="calendar"><div class="wrap"><h2>Следующая встреча с русской литературой</h2><div id="calbox"></div></div></section>
<section class="block" id="kuda-dalshe"><div class="wrap"><h2>История продолжается</h2><div class="jump-links"><a href="https://feb-web.ru/feb/slovo/texts/a50/a50-007-.htm?cmd=p">Прочитать «Слово» целиком →</a><a href="index.html">Выбрать книгу в музее →</a><a href="../ne-sdayutsya/podvig-merkuriy.html">«Меркурий»: корабль, который отказался сдаться →</a></div></div></section></main><footer><div class="wrap">Русская цивилизация · Музей русских писателей</div></footer>
'''
scripts=f'''<script>window.MUSEUM_SCORE={{max:100,awards:{{q:[5,20]}},ranks:[[100,'Внимательный читатель'],[60,'Читатель'],[0,'Гость']],diplomaAt:100}};</script><script src="../../assets/museum-score.js"></script>{audio_cfg}<script src="../../assets/museum-audioguide.js"></script><script>window.MUSEUM_CHOICE_TALE={json.dumps(choice,ensure_ascii=False)};window.MUSEUM_QUIZ={json.dumps(quiz,ensure_ascii=False)};</script><script src="../../assets/museum-choice-tale.js"></script><script src="../../assets/museum-quiz.js"></script><script>window.MUSEUM_SUPPORT={{museum:'Музей русских писателей'}};window.MUSEUM_CHROME={{museum:{{title:'Музей русских писателей',href:'index.html'}},share:{{title:'Слово о полку Игореве',text:{json.dumps(hook,ensure_ascii=False)}}},all:{{href:'index.html',label:'Все писатели'}},city:'../../index.html',random:[]}};</script><script src="../../assets/museum-chrome.js"></script><script src="../../assets/museum-support.js"></script><script src="calendar-literatura.js"></script><script>window.MUSEUM_CALENDAR['01-01'].d={json.dumps(hook,ensure_ascii=False)};window.MUSEUM_CALENDAR['01-01'].href='lit-slovo-emotion.html';window.MUSEUM_CALENDAR_INITIAL='01-01';</script><script src="../../assets/museum-calendar-month.js"></script><script type="application/json" id="museum-score-manifest">{{"maximum":100,"awards":[{{"id":"q","count":5,"each":20}}]}}</script></body></html>'''
(base/'lit-slovo-emotion.html').write_text(head+body+scripts)
print('BUILT',base/'lit-slovo-emotion.html',len(head+body+scripts))
