import json,html,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];D=ROOT/'muzei/pervoprohodcy/nikitin';C=json.load(open(Path(__file__).with_name('content.json')))
RIGHTS={z['id']:z for z in json.load(open(D/'rights.json'))}
def attrs(file,caption):
 k=Path(file).stem
 if k=='atlas-preview':k='atlas'
 z=RIGHTS[k]
 return f' data-rc-exhibit-id="{k}" data-rc-rights-id="rights-{k}" data-title="{esc(caption)}" data-attribution="{esc(z["artist"] or "Автор неизвестен")}" data-explanation="{esc(caption)}"'
def esc(s):return html.escape(s,quote=True)
def fig(file,caption,cls=''):
 return f'<figure class="exhibit {cls}"{attrs(file,caption)}><img src="nikitin/{file}" alt="{esc(caption)}" loading="lazy" decoding="async"><figcaption>{caption}</figcaption></figure>'
route=[
['Тверь',35.91,56.86,'Начало пути','Купец выходит на Волгу с товаром и грамотами. Дорога начинается внутри знакомого торгового мира.','volga.jpg'],
['Нижний Новгород',44,56.33,'Ожидание попутчиков','Две недели Никитин ждёт Хасан-бека, посла ширваншаха. Вместе они спускаются по Волге.','volga.jpg'],
['Низовья Волги',48,46.35,'Потеря поклажи','Нападение лишает Никитина товара. В Дербенте он хлопочет об освобождении попавших в плен спутников.','baku.jpg'],
['Баку',49.87,40.4,'Распутье','Спутники расходятся. Никитин продолжает путь через Каспий и персидские земли.','baku-city.jpg'],
['Ормуз',56.47,27.06,'Второе море','На судне с лошадьми он отправляется в Индию. Переход до Чаула в записках занимает шесть недель.','hormuz.jpg'],
['Чаул',72.93,18.55,'Индийский берег','Морской переход сменяется сухопутной дорогой в Джуннар и Бидар. Начинаются годы жизни в Индии.','chaul.png'],
['Бидар',77.52,17.91,'Наблюдение','Никитин видит торговлю, придворную жизнь и повседневные обычаи. Далёкая страна становится рассказом о людях.','bidar.jpg'],
['Трапезунд',39.72,41,'На обратном пути','После Индийского моря и персидских дорог — выход к Чёрному морю. За ним Крым и дорога к Руси.','trabzon.jpg']]
# Geographic diagram: Natural Earth coast, equirectangular projection; route schematic.
def xy(lon,lat):return ((lon-22)/62*1100,(63-lat)/53*650)
land=json.load(open(Path(__file__).with_name('land.json')));paths=[]
for f in land['features']:
 g=f['geometry'];polys=g['coordinates'] if g['type']=='MultiPolygon' else [g['coordinates']]
 for poly in polys:
  if not any(15<x<90 and 0<y<70 for x,y in poly[0]):continue
  paths.append(' '.join('M'+'L'.join(f'{xy(x,y)[0]:.1f},{xy(x,y)[1]:.1f}' for x,y in ring)+'Z' for ring in poly))
coast=''.join(f'<path fill-rule="evenodd" d="{p}"/>' for p in paths)
# Intermediate vertices make direction visible, not a claim of exact navigation.
coords=[(35.91,56.86),(38,57),(40.9,57.7),(44,56.33),(49.1,55.8),(50.2,53.2),(48,46.35),(48.3,42.1),(49.87,40.4),(52,37),(54.4,31.9),(56.47,27.06),(58.5,23.6),(68,21),(72.93,18.55),(73.9,19.2),(77.52,17.91)]
line=' '.join(f'{xy(x,y)[0]:.1f},{xy(x,y)[1]:.1f}' for x,y in coords)
back=' '.join(f'{xy(x,y)[0]:.1f},{xy(x,y)[1]:.1f}' for x,y in [(77.52,17.91),(73.2,17.6),(60,17),(56.47,27.06),(52.6,29.6),(46.3,38),(39.72,41),(33.6,44.5),(35,54.8)])
circles=''.join(f'<circle class="route-dot" data-stop="{i}" cx="{xy(r[1],r[2])[0]:.1f}" cy="{xy(r[1],r[2])[1]:.1f}" r="7"/>' for i,r in enumerate(route))
svg=f'<svg id="route-map" viewBox="0 0 1100 650" role="img" aria-label="Схема пути от Твери по Волге, через Каспий и Ормуз в Индию, обратно через Трапезунд"><defs><pattern id="grid" width="55" height="65" patternUnits="userSpaceOnUse"><path d="M 55 0 L 0 0 0 65" fill="none" stroke="#b8a474" stroke-opacity=".12"/></pattern></defs><rect width="1100" height="650" fill="#101f29"/><g fill="#293e42" stroke="#728784" stroke-width=".7">{coast}</g><rect width="1100" height="650" fill="url(#grid)"/><polyline points="{line}" fill="none" stroke="#e9bd6b" stroke-width="3.5"/><polyline points="{back}" fill="none" stroke="#8cc5cf" stroke-width="2.5" stroke-dasharray="7 7"/>{circles}</svg>'
(D/'route.svg').write_text(svg)
story=''.join(f'<article class="chapter" id="chapter-{i+1}"><div class="chapter-image">{fig(ch["image"],ch["caption"])}</div><div class="chapter-copy"><div class="eyebrow">Глава {i+1:02d} · {ch["place"]}</div><h3>{ch["title"]}</h3>'+''.join('<p>'+p+'</p>' for p in ch['body'])+'</div></article>' for i,ch in enumerate(C['chapters']))
rights=json.load(open(D/'rights.json'))
rightshtml=''.join(f'<li data-rc-rights-id="rights-{r["id"]}"><a href="{esc(r["source"])}">{esc(r["id"])}</a> · {esc(r["artist"] or "Автор не указан")} · {esc(r["license"] or "См. карточку")}</li>' for r in rights)
page='''<!DOCTYPE html><html lang="ru" data-museum="explorers" data-fabric="atlas"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Афанасий Никитин — Из Твери в Индию XV века · Русские первопроходцы</title><meta name="robots" content="noindex,follow"><meta name="description" content="Три моря, шесть решений и записки, вернувшиеся на Русь без автора. Пройдите путь Афанасия Никитина: карта, исторический атлас, рассказ и игра."><link rel="canonical" href="https://arabelthera-dot.github.io/rc-museum-preview/muzei/pervoprohodcy/exp-nikitin-1468.html"><meta property="og:title" content="До дома добрались его тетради"><meta property="og:description" content="Афанасий Никитин. Из Твери в Индию XV века."><meta property="og:image" content="https://arabelthera-dot.github.io/rc-museum-preview/muzei/pervoprohodcy/nikitin/atlas-preview.jpg"><link rel="stylesheet" href="nikitin/page.css"></head><body>
<a class="skip" href="#story">Перейти к истории</a>
<header class="top"><div class="b1">Русские первопроходцы</div><div class="b2">Первый цифровой музей достижений России · Цивилизация первенств — что Россия дала миру раньше всех</div><div class="score" id="scoreBox">⭐ <span id="score">0</span> / 100</div></header>
<nav class="crumbs" aria-label="Хлебные крошки"><a href="../../index.html">Русская цивилизация</a><span> › </span><a href="index.html">Первопроходцы</a><span> › </span>Афанасий Никитин</nav>
<div class="hero-scene"><img src="nikitin/atlas-preview.jpg" alt="Карта мира Фра Мауро: синие моря, золотистая суша, сотни названий" fetchpriority="high"></div>
<div class="scene-caption scene-cap">Мир Фра Мауро, XV век · копия У. Фрейзера, 1806. Юг сверху. <a href="#atlas">Рассмотреть карту ↗</a></div>
<header class="hero-lead"><div class="date-chip">1 января · Путешествие XV века</div><div class="who">Афанасий Никитин · тверской купец и путешественник</div><h1>Из Твери —<br><em>в Индию XV века</em></h1><p class="hook">HOOK</p><div class="hero-btns"><a class="gbtn" href="#story">Читать историю ↓</a><a class="gbtn sec" href="#audioguide">🎧 Слушать аудиогид</a></div></header>
<div class="hero-under"><div class="stamp"><b>Три моря</b><span>Каспийское · Индийское · Чёрное</span></div><div class="stamp"><b>XV век</b><span>Годы пути уточняют исследователи</span></div><div class="stamp"><b>Один купец</b><span>В центре истории — его взгляд</span></div><div class="stamp"><b>«Хождение»</b><span>Главный итог, дошедший до нас</span></div></div>
<nav class="daynav" aria-label="Разделы страницы"><a href="#rolik">Ролик</a><a href="#put">Путь</a><a href="#atlas">Атлас</a><a href="#story">История</a><a href="#voice">Документ</a><a href="#pohod">Пройти три моря</a><a href="#quiz">Проверить себя</a><a href="#calendar">Календарь</a></nav>
<main>
<section id="rolik" class="block"><div class="section-head"><span class="eyebrow">01 / Войти в историю</span><h2>Товар пропал.<br>Рассказ остался.</h2><p>Короткое вступление — о том, что может остаться от путешествия, которое не удалось закончить.</p></div><video controls playsinline preload="none" poster="nikitin/film-poster.jpg"><source src="nikitin/film.mp4" type="video/mp4"><track kind="subtitles" srclang="ru" label="Русский" src="nikitin/film.vtt" default></video><p class="caption">Авторский музейный ролик из картографических и фотографических материалов. Позднейшие виды мест пути. Голос синтезирован.</p></section>
<section id="audioguide" class="block"></section>
<section id="put" class="block wide"><div class="section-head"><span class="eyebrow">02 / География решения</span><h2>Дорога, которая<br>меняет цель</h2><p>Выбирай остановки. Следи, как торговая поездка становится жизнью вдали от Руси.</p></div><div class="route-layout"><div class="route-visual">MAP<div class="map-legend"><span>━ Путь в Индию</span><span>┄ Возвращение</span></div></div><div class="route-info" aria-live="polite"><span id="route-count" class="eyebrow"></span><h3 id="route-title"></h3><p id="route-event" class="accent"></p><p id="route-text"></p><div class="route-arrows"><button id="route-prev" class="gbtn sec" aria-label="Предыдущая остановка">←</button><button id="route-next" class="gbtn" aria-label="Следующая остановка">Следующая →</button></div></div></div><div id="route-buttons" class="chips">ROUTEBUTTONS</div><p class="caption">Объясняющая схема по «Хождению». Берега: Natural Earth, public domain. Линии связывают места, а не восстанавливают точный трек. На карте не показаны все промежуточные стоянки.</p></section>
<section id="atlas" class="block wide"><div class="section-head"><span class="eyebrow">03 / Смотреть глазами эпохи</span><h2>Переверни привычный мир</h2><p>Здесь юг наверху. Европа — внизу справа, Индийское море — вверху. Приблизь карту и попробуй заново собрать географию знакомого мира.</p></div><div id="atlas-viewer" aria-label="Историческая карта с увеличением"></div><div class="atlas-tools"><button class="gbtn sec" data-zoom="1.6" aria-label="Приблизить карту">＋</button><button class="gbtn sec" data-zoom="0.625" aria-label="Отдалить карту">−</button><button class="gbtn sec" id="atlas-home">Вся карта</button><button class="gbtn sec" id="atlas-rotate">Повернуть на 180°</button></div><div class="chips"><button data-atlas=".62,.82,3">Европа внизу</button><button data-atlas=".39,.42,3">Индия слева</button><button data-atlas=".40,.24,3">Индийское море</button></div><div class="document-note"><b>Чья это карта?</b><p>Фра Мауро, венецианский картограф XV века. Перед нами копия Уильяма Фрейзера 1806 года. Это представление о мире близкой эпохи, а не принадлежавшая Никитину карта. Сведения о том, что он ею пользовался, отсутствуют.</p><a href="nikitin/atlas-detail.jpg" target="_blank">Открыть лист отдельно, 5037 × 5032 px ↗</a></div></section>
<section id="story" class="block wide"><div class="section-head"><span class="eyebrow">04 / Шесть глав</span><h2>До дома добрались<br>его тетради</h2><p>Большой рассказ по «Хождению за три моря». Фотографии показывают места в более поздние времена; голос XV века сохраняется в тексте.</p></div>STORY</section>
<section id="voice" class="block"><div class="section-head"><span class="eyebrow">05 / Голос документа</span><h2>Спросить — и услышать текст</h2><p>Ответы раскрывают свидетельства «Хождения». Это чтение документа с пояснениями.</p></div><div class="chips" id="voice-buttons"><button data-voice="0">Почему идти дальше?</button><button data-voice="1">Какие три моря?</button><button data-voice="2">Что значит дом?</button><button data-voice="3">Кто сохранил записки?</button></div><div id="voice-answer" class="document-note" aria-live="polite"></div></section>
<section id="deep" class="block"><div class="section-head"><span class="eyebrow">06 / Читать внимательнее</span><h2>Что мы знаем.<br>О чём спорим.</h2></div><details><summary>Почему у путешествия разные годы?</summary><p>В популярном материале РГО назван путь 1466–1472 годов. Комментарий к научному изданию «Библиотеки литературы Древней Руси» приводит 1468–1475 годы. Сам летописец отмечает отсутствие прямой даты выхода в тетрадях. Поэтому мы не связываем страницу с годовщиной отправления. 1 января — условное место в музейном календаре.</p></details><details><summary>Он был первым человеком в Индии?</summary><p>Нет. Никитин приехал в населённую страну с городами, государствами и многовековой торговлей. Значение его пути — раннее подробное русское свидетельство о жизни в Индии. Он побывал там раньше плавания Васко да Гамы 1498 года, но шёл другой дорогой и решал другие задачи.</p></details><details><summary>Всё названное он видел своими глазами?</summary><p>В «Хождении» есть сведения о портах и землях далеко за пределами уверенно восстанавливаемого маршрута. Само упоминание места не доказывает посещения. В тексте различаются собственные переходы и услышанные сообщения. Это особенно важно для рассказов о далёких рынках.</p></details><details><summary>Сохранилась его собственная тетрадь?</summary><p>Мы читаем произведение по рукописным спискам. Научное издание сопоставляет разные редакции и указывает разночтения. Летописная приписка сообщает о привезённых купцами тетрадях, но это не позволяет назвать каждый сохранившийся список автографом Никитина.</p></details>BOOK</section>
<section id="world" class="block wide"><div class="section-head"><span class="eyebrow">07 / Мир вокруг путешественника</span><h2>Войти в чужой мир.<br>Не перестать быть собой.</h2></div><div class="world-grid"><div><h3>Никитин</h3><span class="eyebrow">XV век · путь из Руси</span><p>Речная, сухопутная и морская дорога. Купеческие надежды, потеря товара, годы наблюдений. Главное сохранившееся свидетельство — личные записки.</p></div><div><h3>Васко да Гама</h3><span class="eyebrow">1498 · путь из Португалии</span><p>Морская экспедиция достигает Индии вокруг Африки. Это другой маршрут и государственная задача. Хронологическое сопоставление помогает увидеть ранний русский опыт, не смешивая две истории.</p></div></div>HAMPI<p>Никитин узнавал об Индии изнутри её торговой жизни. В его рассказ входят и соседние земли, о которых говорят собеседники. Виджаянагар — один из таких больших миров. Фотография Хампи здесь помогает представить исторический контекст; она не служит доказательством визита Никитина.</p><div class="gallery">EXTRA</div></section>
<section id="pohod" class="block wide"><div class="section-head"><span class="eyebrow">08 / Твоя дорога · 60 очков</span><h2>Пройти три моря</h2><p>Шесть решений: как подготовиться, что делать после потери товара, на что опереться в чужой стране и что сохранить для дома.</p></div><div class="game-disclosure">Учебные альтернативы. Последствия описаны словами; вымышленных потерь людей и денег нет. После каждого выбора открывается документальная история.</div><div id="pohodbox"></div></section>
<section id="order" class="block"><span class="eyebrow">09 / Собери путь · 20 очков</span><h2>Какое море было следующим?</h2><p>Нажми три моря в порядке, который Никитин указал в названии своего путешествия. Ошибка оставляет возможность попробовать снова.</p><div class="chips" id="sea-buttons"><button data-sea="2">Чёрное</button><button data-sea="0">Каспийское</button><button data-sea="1">Индийское</button></div><p id="sea-feedback" aria-live="polite">Первое море → второе → третье</p><button class="gbtn sec" id="sea-reset">Начать порядок заново</button></section>
<section id="quiz" class="block"><span class="eyebrow">10 / Проверь наблюдательность · 20 очков</span><h2>Что осталось после дороги?</h2><div id="quiz-box"></div></section>
<section id="result" class="block"><span class="eyebrow">Твой итог</span><h2 id="rank">Читатель дороги</h2><progress id="progress" value="0" max="100" aria-label="Очки прохождения"></progress><p>Пройдено на <b id="result-score">0</b> из 100 очков. Игра — 60, порядок морей — 20, два вопроса — 20. Повторное прохождение не удваивает результат.</p><button class="gbtn sec" id="diploma">Сохранить свидетельство путешествия</button><p id="diploma-note" aria-live="polite"></p></section>
<section id="calendar" class="block"><span class="eyebrow">Музейный календарь</span><h2>Открывать по одной истории</h2><div id="calbox"></div><p class="caption">Никитин занимает 1 января по утверждённому составу. Привязка условная. <a href="../../review/pervoprohodcy-calendar-january.html">Посмотреть весь январский состав →</a></p></section>
<section id="next" class="block"><span class="eyebrow">Куда дальше</span><h2>Ещё одна дорога.<br>Ещё один поворот.</h2><div class="next-grid"><a class="next-card" href="exp-dezhnev-1648.html"><span>Семён Дежнёв · 1648</span><h3>За клыком — между материками</h3><p>Промысловый поход проходит пролив, о значении которого участники ещё не знают. Открыть экспедицию →</p></a><a class="next-card" href="../../review/pervoprohodcy-calendar-january.html"><span>Январь · 31 история</span><h3>Выбрать следующий горизонт</h3><p>Утверждённый календарь музея с героями, хуками и будущими интерактивами. Открыть календарь →</p></a></div></section>
<section id="sources" class="block sources"><h2>Источники и изображения</h2><p>Основа рассказа — древнерусский текст «Хождения за три моря», памятник XV века в общественном достоянии. Изложение на странице авторское. Прямые цитаты отмечены кавычками.</p><ol><li><a href="https://azbyka.ru/otechnik/Istorija_Tserkvi/biblioteka-literatury-drevnej-rusi-tom-7/11">Библиотека литературы Древней Руси, том 7: текст, перевод и научные комментарии</a>. Использованы древнерусский оригинал и справки о списках.</li><li><a href="https://rgo.ru/activity/redaction/news/08-24/">Русское географическое общество, 29 августа 2024</a>: общий маршрут и судьба путешественника.</li><li><a href="https://lib.tstu.tver.ru/khozhdenie-za-tri-morya.html">Библиотека Тверского государственного технического университета</a>: издания «Хождения».</li></ol><details><summary>Авторы, лицензии и происхождение изображений</summary><ul>RIGHTS</ul><p>Снимки оптимизированы для экрана. Полные паспорта: <a href="nikitin/rights.json">реестр изображений</a>. Карта пути: Natural Earth, public domain; схема маршрута — редакционная.</p></details></section>
</main><footer><p>Русские первопроходцы · Русская цивилизация</p><a href="#top" id="to-top">Вернуться к началу ↑</a></footer>
<script type="application/json" id="museum-score-manifest">{"maximum":100,"awards":[{"id":"journey","count":6,"each":10},{"id":"seas","max":20},{"id":"quiz","count":2,"each":10}]}</script>
<script>window.NIKITIN_ROUTE=ROUTEJSON;window.MUSEUM_CHROME={museum:{title:'Русские первопроходцы',href:'index.html'},all:{href:'index.html',label:'Все экспедиции'},city:'../../index.html',share:{title:'Афанасий Никитин — Из Твери в Индию',text:'До дома добрались его тетради. Пройди три моря.'}};window.MUSEUM_SUPPORT={museum:'Русские первопроходцы',peak:'#put'};</script>
<script src="vendor/openseadragon/openseadragon.min.js"></script><script src="../../assets/museum-choice-run.js"></script><script src="nikitin/page.js"></script><script src="nikitin/calendar.js"></script><script src="../../assets/museum-calendar-month.js"></script><script src="../../assets/museum-audioguide.js"></script><script src="../../assets/museum-chrome.js"></script><script src="../../assets/museum-support.js"></script><script defer src="../../assets/analytics.js"></script></body></html>'''
for k,v in {'HOOK':C['hook'],'MAP':svg,'ROUTEBUTTONS':''.join(f'<button data-route="{i}">{i+1:02d} {r[0]}</button>' for i,r in enumerate(route)),'STORY':story,'BOOK':fig('book.jpg','«Хожение за три моря». Введение к изданию И. И. Срезневского, 1857. Печатная книга, не автограф Никитина.','book'),'HAMPI':fig('hampi.jpg','Хампи, руины Виджаянагара. Вячеслав Аргенберг, CC BY 4.0. Современная фотография; исторический контекст, не остановка маршрута.'),'EXTRA':fig('baku-city.jpg','Баку, 1890. Поль Надар. Позднейший вид города у Каспийского моря.')+fig('hormuz-red.jpg','Ормуз сегодня. Мехди Закери, CC BY 4.0. Берег острова на пути к Индийскому морю.')+fig('chaul.png','Чаул. Изображение из «Asia Portuguesa», Мануэл де Фария-и-Соуза, XVII век. Позднейшая португальская крепость; не облик города при Никитине.'),'RIGHTS':rightshtml,'ROUTEJSON':json.dumps(route,ensure_ascii=False)}.items():page=page.replace(k,v)
a=json.load(open(D/'audio.json'));config={'audioSrc':'nikitin/audioguide.mp3','heading':'Шесть остановок с экскурсоводом','lead':'Смотри на реку, море и города вместе с голосом. Аудиогид предлагает наблюдения и вопросы, которые можно продолжить на странице.','stops':a['stops'],'transcript':a['transcript'],'note':'Голос синтезирован. Текст экскурсии доступен ниже.'};page=page.replace('<script src="../../assets/museum-audioguide.js">','<script>window.MUSEUM_AUDIOGUIDE='+json.dumps(config,ensure_ascii=False).replace('\"audioSrc\":', 'audioSrc:')+'</script><script src="../../assets/museum-audioguide.js">')
page=page.replace('<div class="hero-scene">','<div class="hero-scene"'+attrs('atlas-preview.jpg','Карта мира Фра Мауро, XV век, копия 1806')+'>');page=page.replace('Авторы, лицензии и происхождение изображений','Авторы, лицензии и происхождение изображений · <span data-rc-count="exhibits">'+str(len(RIGHTS))+'</span>')
page=page.replace('<body>','<body id="top">')
(ROOT/'muzei/pervoprohodcy/exp-nikitin-1468.html').write_text(page)
print('Built page, chapters:',len(C['chapters']))
