from pathlib import Path
import json,hashlib
root=Path(__file__).resolve().parents[2];d=root/'muzei/pervoprohodcy/nikitin';c=json.load(open(Path(__file__).with_name('content.json')));r=json.load(open(d/'rights.json'))
sources=[{'source_id':'src-text','title_ru':'Хождение за три моря. БЛДР, том 7','publisher_ru':'Наука; электронное воспроизведение Азбука веры','url':'https://azbyka.ru/otechnik/Istorija_Tserkvi/biblioteka-literatury-drevnej-rusi-tom-7/11','source_type':'academic','language':'ru','checked_at':'2026-09-08'},{'source_id':'src-rgo','title_ru':'За три моря','publisher_ru':'Русское географическое общество','url':'https://rgo.ru/activity/redaction/news/08-24/','source_type':'official_publication','language':'ru','checked_at':'2026-09-08'}]
objects=[];images=[]
for z in r:
 objects.append({'object_id':'obj-'+z['id'],'object_type':'map' if z['id']=='atlas' else 'documentary-image','title_ru':z['title'],'date_display_ru':'XV век, копия 1806' if z['id']=='atlas' else 'Позднейшее изображение; см. атрибуцию','attribution_ru':z['artist'] or 'Автор неизвестен','holder_ru':'Wikimedia Commons','source_ids':['src-text']})
 images.append({'image_id':'img-'+z['id'],'object_id':'obj-'+z['id'],'local_path':'../../muzei/pervoprohodcy/nikitin/'+z['file'],'sha256':hashlib.sha256((d/z['file']).read_bytes()).hexdigest(),'source_url':z['source'],'credit_ru':(z['artist'] or 'Автор неизвестен')+'; '+z['license'],'alt_ru':z['title'],'rights':{'status':'cleared','basis_ru':z['license']+' по карточке Wikimedia Commons; атрибуция размещена на странице','checked_at':'2026-09-08','commercial_use':'allowed','derivatives':'allowed','ai_modification':'not_used','reviewer':'codex-bot'}})
p={'schema_version':'1.0.0','museum_id':'pervoprohodcy','issue_id':'nikitin-1468','content_family_id':'nikitin-three-seas','version':'1.0.0','identity':{'title_ru':c['title'],'slug':'exp-nikitin-1468','calendar_slot':'01-01','museum_name_ru':'Русские первопроходцы','language':'ru','summary_ru':c['hook']},'lifecycle':{'current':'preview','history':[{'status':'preview','at':'2026-09-08T15:00:00Z','actor':'codex-bot','note_ru':'Собрано по принятому предложению, подготовка к личной приёмке Сергея'}]},'narrative':{'visitor_promise_ru':'Пройти торговую дорогу и увидеть, как сохраняется знание о чужой жизни','hook_ru':c['hook'],'turn_ru':'Товар потерян, но наблюдение продолжается','conclusion_ru':'Дорога человека оборвалась; дорога текста продолжилась','depths':{'see':'Ролик и карта','understand':'Шесть глав и решения','research':'Первичный текст и глубокий зум'}},'interactive':{'title_ru':'Пройти три моря','type':'choice_path','visitor_action_ru':'Выбрать шесть решений и сопоставить их последствия с историческим маршрутом','exclusive_insight_ru':'Каждое решение показывает новую дорожную задачу и предел известного','wow_effect_ru':'В конце вся личная цепочка решений сопоставляется с путём Никитина','text_alternative_ru':'Весь исторический путь и объяснения доступны в шести главах рассказа','engine':'museum-choice-run.js, opt-in journey','unique_to_issue':True},'claims':[{'claim_id':'claim-journey','text_ru':'Никитин достиг Индии, оставил записки и умер на обратном пути до Смоленска','kind':'fact','key_claim':True,'confidence':'verified','source_ids':['src-text','src-rgo']}],'sources':sources,'objects':objects,'images':images,'risks':{k:{'level':'low','reason_ru':reason,'mitigation_ru':mit,'approved_by':None} for k,reason,mit in [('historical','Даты расходятся; позднейшие виды не равны XV веку','Различия дат и статусы изображений подписаны рядом'),('legal','Свободные лицензии требуют атрибуции','Источник, автор и лицензия размещены'),('reputational','Результат ещё не принят владельцем','Статус preview сохраняется до решения Сергея')]},'seo':{'title_ru':c['title'],'description_ru':c['hook'],'h1_ru':c['title'],'canonical_url':'https://arabelthera-dot.github.io/rc-museum-preview/muzei/pervoprohodcy/exp-nikitin-1468.html','index_state':'noindex','primary_query_ru':'Афанасий Никитин Хождение за три моря','og_image_id':'img-atlas'},'media':[{'media_id':'media-'+kind,'kind':kind,'platform':'web','status':'review','path':path} for kind,path in [('page','../../muzei/pervoprohodcy/exp-nikitin-1468.html'),('audio','../../muzei/pervoprohodcy/nikitin/audioguide.mp3'),('video','../../muzei/pervoprohodcy/nikitin/film.mp4'),('transcript','../../muzei/pervoprohodcy/nikitin/audio.json')]],'publication':{'blockers':['Личная приёмка Сергея для основного музейного каталога'],'approvals':{'fact_check':True,'rights':True,'editorial':True},'target_path':'muzei/pervoprohodcy/exp-nikitin-1468.html'}}
def ids(x):
 if isinstance(x,dict):
  return {k:('rc:nikitin:'+v if (k.endswith('_id') and isinstance(v,str)) else ['rc:nikitin:'+s for s in v] if k=='source_ids' else ids(v)) for k,v in x.items()}
 if isinstance(x,list):return [ids(v) for v in x]
 return x
p=ids(p)
Path(__file__).with_name('issue.json').write_text(json.dumps(p,ensure_ascii=False,indent=2))
