(function(){'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const awards=new Map();function award(key,value){if(awards.has(key))return;awards.set(key,value);const n=[...awards.values()].reduce((a,b)=>a+b,0);$('#score').textContent=n;$('#result-score').textContent=n;$('#progress').value=n;$('#rank').textContent=n===100?'Хранитель дорожных записок':n>=60?'Исследователь трёх морей':'Читатель дороги';}
let ri=0;function route(i){ri=i;let r=window.NIKITIN_ROUTE[i];$('#route-count').textContent=`Остановка ${i+1} / 8`;$('#route-title').textContent=r[0];$('#route-event').textContent=r[3];$('#route-text').textContent=r[4];$$('[data-route]').forEach(x=>{x.classList.toggle('on',+x.dataset.route===i);x.setAttribute('aria-pressed',+x.dataset.route===i)});$$('.route-dot').forEach(x=>x.classList.toggle('on',+x.dataset.stop===i));$('#route-prev').disabled=i===0;$('#route-next').disabled=i===7;}
$$('[data-route]').forEach(b=>b.onclick=()=>route(+b.dataset.route));$('#route-prev').onclick=()=>route(Math.max(0,ri-1));$('#route-next').onclick=()=>route(Math.min(7,ri+1));route(0);
let viewer,rotation=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function initAtlas(){if(viewer||!window.OpenSeadragon)return;viewer=OpenSeadragon({id:'atlas-viewer',prefixUrl:'vendor/openseadragon/images/',tileSources:{type:'image',url:'nikitin/atlas-detail.jpg'},showNavigationControl:false,showNavigator:false,animationTime:reduced?0:.65,maxZoomPixelRatio:1.5,visibilityRatio:.5,gestureSettingsMouse:{scrollToZoom:false},gestureSettingsTouch:{pinchToZoom:true}});window.nikitinAtlas=viewer;}
new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))initAtlas()},{rootMargin:'250px'}).observe($('#atlas-viewer'));
$$('[data-zoom]').forEach(b=>b.onclick=()=>{initAtlas();if(viewer.viewport){viewer.viewport.zoomBy(+b.dataset.zoom);viewer.viewport.applyConstraints();}});$('#atlas-home').onclick=()=>{initAtlas();viewer.viewport.setRotation(0);rotation=0;viewer.viewport.goHome();};$('#atlas-rotate').onclick=()=>{initAtlas();rotation=rotation?0:180;viewer.viewport.setRotation(rotation);};$$('[data-atlas]').forEach(b=>b.onclick=()=>{initAtlas();let [x,y,z]=b.dataset.atlas.split(',').map(Number);rotation=0;viewer.viewport.setRotation(0);viewer.viewport.panTo(new OpenSeadragon.Point(x,y));viewer.viewport.zoomTo(z);});
const voices=[
['«А хто был должен, а тот пошел, куды его очи понесли».','Никитин различает судьбы спутников после ограбления. Долг делает возвращение труднее. Продолжение пути не нужно украшать выдуманным изначальным планом открыть Индию.'],
['«Первое море Дербеньское… второе море Индѣйское… третие море Черное».','Названия раскрывают устройство путешествия: Каспий, морской путь в Индию и Чёрное море на обратной дороге. Это три моря всего рассказа, а не три подряд пересечённых моря по дороге в Индию.'],
['«А Русь еръ тангрыд сакласын».','Фраза из многоязычного фрагмента с пожеланием, чтобы Бог хранил Русь. Чужие слова и память о своей земле сосуществуют внутри одной записи. Перевод и толкование фрагмента смотри в научном издании.'],
['«А писание своей рукою писал».','Это слова летописной приписки о Никитине. Далее она сообщает: тетради привезли купцы в Москву Василию Мамыреву. Голос автора и голос человека, сообщающего о судьбе текста, нужно различать.']];
function voice(i){$('#voice-answer').innerHTML='<blockquote>'+voices[i][0]+'</blockquote><p>'+voices[i][1]+'</p><p class="caption">Древнерусский текст, XV век; пунктуация адаптирована. <a href="https://azbyka.ru/otechnik/Istorija_Tserkvi/biblioteka-literatury-drevnej-rusi-tom-7/11">Открыть научное издание ↗</a></p>';$$('[data-voice]').forEach(b=>b.classList.toggle('on',+b.dataset.voice===i));}$$('[data-voice]').forEach(b=>b.onclick=()=>voice(+b.dataset.voice));voice(0);
const stages=[
{when:'Перед дорогой',title:'На что потратить последние дни подготовки?',text:'Можно проверить товар, найти попутчиков или собрать сведения о пути. Времени на всё не хватает. Выбери главную опору своей поездки.',truth:'Никитин шёл с грамотами и в Нижнем Новгороде две недели ждал посла Хасан-бека. Посольское сопровождение оказалось важным, хотя и не спасло от ограбления.',options:[{label:'Дождаться попутчиков и проверить разрешения',echo:'Ты выбираешь связи и совместный переход. Это уменьшает одиночество в дороге, но не даёт гарантии безопасности.'},{label:'Сосредоточиться на качестве товара',echo:'Ты защищаешь будущую сделку. Теперь для следующего перехода всё равно придётся искать людей и разрешения.'},{label:'Расспросить бывалых о дороге',echo:'В твоей тетради появляются чужие сведения. Они помогут задавать вопросы, но часть придётся проверить на месте.'}]},
{when:'Низовья Волги',title:'Товар потерян. Куда теперь?',text:'Поездка больше не обещает прежней прибыли. Спутники выбирают разные дороги. Твоё решение определяет, какую задачу придётся решать следующей.',truth:'После ограбления и освобождения пленных спутники разошлись. Одни вернулись на Русь, другие остались работать в Шемахе и Баку. Никитин продолжил путь.',options:[{label:'Искать возможность вернуться на Русь',echo:'Твоя ветка поворачивает домой. Следующая трудность — найти средства и попутчиков для возвращения без товара.'},{label:'Остаться в торговом городе и искать работу',echo:'Твоя ветка задерживается у Каспия. На первый план выходят жильё, заработок и знакомства в новом городе.'},{label:'Продолжить путь на юг',echo:'Твоя ветка ведёт через персидские земли. Теперь нужно заново искать товар и возможность содержать себя.'}]},
{when:'Ормуз',title:'Море начинается с разговора на пристани',text:'Впереди переход в Индию с конём. Что выяснить в первую очередь, прежде чем договориться о месте на судне?',truth:'Никитин отплыл из Ормуза на таве с лошадьми. В записках он указывает шесть недель морского пути до Чаула и промежуточные остановки.',options:[{label:'Условия перевозки коня и промежуточные стоянки',echo:'Ты собираешь сведения, от которых зависит перевозка живого товара. Дорога становится последовательностью решаемых задач.'},{label:'Только самую низкую цену проезда',echo:'Ты узнаёшь стоимость места. Условия для животного и снабжение остаются неизвестными — их придётся выяснять отдельно.'},{label:'Только рассказы о богатстве индийских рынков',echo:'Ты укрепляешь надежду на прибыль. Эти рассказы пока не отвечают на вопрос, как пережить сам переход.'}]},
{when:'Индия',title:'Чужой порядок. У кого искать помощь?',text:'Ты не знаешь всех правил места, куда приехал. Случилась трудность с товаром. Выбери способ действовать в незнакомом окружении.',truth:'В Джуннаре местный правитель отнял у Никитина коня и поставил условие о смене веры. Заступничество Ходжи Мухаммеда помогло вернуть животное. Это конкретный эпизод, не правило обо всей Индии.',options:[{label:'Обратиться к знакомому, понимающему местные порядки',echo:'Ты выбираешь посредника. Теперь многое зависит от его возможностей, отношений и готовности заступиться.'},{label:'Пытаться решить всё одному',echo:'Ты сохраняешь независимость, но остаёшься без знания местных связей. Следующий шаг потребует особенно внимательного разговора.'},{label:'Сразу искать дорогу в другой город',echo:'Ты выбираешь уход от конфликта. Но сначала нужно понять, можно ли вообще уехать и что будет с твоим имуществом.'}]},
{when:'Возвращение',title:'Старая дорога стала опасной',text:'Ты хочешь на Русь. Вести о войнах меняют представление о знакомых путях. Каким сведениям придать наибольший вес?',truth:'Перед возвращением Никитин перечисляет направления, ставшие недоступными из-за смут. Он вновь пересекает Индийское море, идёт через персидские земли и достигает Трапезунда.',options:[{label:'Недавним сообщениям людей, прошедших нужный участок',echo:'Ты обновляешь своё знание о дороге. Даже знакомый маршрут приходится проверять заново.'},{label:'Тому, что было безопасно несколько лет назад',echo:'Ты опираешься на собственный опыт. Его слабое место — перемены, произошедшие за время твоего отсутствия.'},{label:'Самой короткой линии на схеме',echo:'Ты сокращаешь расстояние на бумаге. На местности ещё остаются война, пропуск, горы и возможность найти ночлег.'}]},
{when:'Дорожная тетрадь',title:'Что ты передашь людям дома?',text:'Место в тетради ограничено. Какой способ записи оставит читателю больше надёжного знания?',truth:'В «Хождении» сохранились личные наблюдения, торговые сведения, молитвы и услышанные рассказы. Купцы привезли тетради в Москву после смерти автора. Читая текст, мы различаем эти голоса и способы знания.',options:[{label:'Отделить увиденное своими глазами от услышанного',echo:'Твой читатель сможет проверить, где кончается личное свидетельство. Сомнение тоже становится полезной частью знания.'},{label:'Оставить только самые удивительные рассказы',echo:'Получится захватывающая тетрадь. Но без происхождения сведений читателю будет трудно отличить наблюдение от слуха.'},{label:'Записать только расходы и цены',echo:'Тетрадь поможет будущему купцу считать дорогу. Повседневная жизнь людей и твой личный опыт останутся за её пределами.'}]}];
window.RUN_NIKITIN={mode:'journey',pointsPerStage:10,stages,finale:{title:'Твой путь рядом с историческим',text:'Сравни всю цепочку решений. Мы не меняли биографию Никитина: учебные альтернативы показали, какие задачи возникали бы при твоём выборе. За каждую изученную развилку — 10 очков.'}};
window.nikitinRun=MuseumChoiceRun.init({mount:'#pohodbox',data:RUN_NIKITIN,onPoints:(n,i)=>award('journey-'+i,n)});
let sea=0;$('#sea-reset').onclick=()=>{sea=0;$$('[data-sea]').forEach(b=>{b.disabled=false;b.classList.remove('ok')});$('#sea-feedback').textContent='Первое море → второе → третье';$('#sea-feedback').className='';};$$('[data-sea]').forEach(b=>b.onclick=()=>{let f=$('#sea-feedback');if(+b.dataset.sea!==sea){f.textContent='Пока не так. Начни с моря у устья Волги; Чёрное будет на обратном пути.';f.className='error';return;}b.disabled=true;b.classList.add('ok');sea++;f.className='feedback';f.textContent=sea===3?'Каспийское → Индийское → Чёрное. Название охватывает весь путь, включая возвращение. +20 очков.':'Верно. Выбери следующее море.';if(sea===3)award('seas',20);});
const quizzes=[{q:'Какой итог путешествия мы можем исследовать сегодня?',opts:['Авторские тетради, без изменений лежащие в музее','Текст «Хождения», сохранившийся в списках','Подробную карту, начерченную Никитиным'],correct:1,why:'Произведение дошло в рукописных списках. Их изучение не равно работе с сохранившимся автографом.'},{q:'Почему на странице стоит 1 января?',opts:['Это установленный день выхода из Твери','Это день рождения Никитина','Это условная позиция в утверждённом календаре'],correct:2,why:'У путешествия нет доказанной привязки к этому дню. Условная дата помогает устроить музейный год.'}];
quizzes.forEach((q,i)=>{let box=document.createElement('div');box.className='quiz-question';box.innerHTML='<h3>'+q.q+'</h3><div class="quiz-options"></div><p class="feedback" aria-live="polite"></p>';q.opts.forEach((o,j)=>{let b=document.createElement('button');b.textContent=o;b.onclick=()=>{let f=box.querySelector('.feedback');if(j!==q.correct){f.textContent='Попробуй ещё раз. '+(i===0?'Вспомни разницу между авторской тетрадью и списком.':'Дата в календаре музея может быть условной.');f.classList.add('error');b.setAttribute('aria-pressed','false');return;}f.textContent=q.why+' +10 очков.';f.classList.remove('error');b.classList.add('ok');box.querySelectorAll('button').forEach(x=>x.disabled=true);award('quiz-'+i,10);};box.querySelector('.quiz-options').appendChild(b)});$('#quiz-box').appendChild(box)});
$('#diploma').onclick=()=>{const score=$('#score').textContent;const contents='Русские первопроходцы\nАфанасий Никитин · Три моря\n\nРезультат: '+score+' / 100\n'+$('#rank').textContent+'\n\nМои решения:\n'+window.nikitinRun.state.choices.map((o,i)=>(i+1)+'. '+o.label).join('\n')+'\n\nhttps://arabelthera-dot.github.io/rc-museum-preview/muzei/pervoprohodcy/exp-nikitin-1468.html';let u=URL.createObjectURL(new Blob([contents],{type:'text/plain;charset=utf-8'}));let a=document.createElement('a');a.href=u;a.download='Три-моря-мой-путь.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);$('#diploma-note').textContent='Свидетельство содержит твой фактический результат и выбранные решения.';};
})();
