/* Exhibit-specific comparison. The shape is schematic; material layers follow Pudov 2022. */
(()=>{'use strict';const root=document.getElementById('material-lab');if(!root)return;
const key='rc-chest-material-v1',required=['solid-red','cut-red','cut-green','cut-none'];let iron='cut',lining='red',seen=new Set();
try{const s=JSON.parse(localStorage.getItem(key)||'{}');if(['solid','cut'].includes(s.iron))iron=s.iron;if(['red','green','none'].includes(s.lining))lining=s.lining;(s.seen||[]).filter(x=>required.includes(x)).forEach(x=>seen.add(x))}catch{}
function paint(){const state=iron+'-'+lining;if(required.includes(state))seen.add(state);document.getElementById('lab-holes').style.display=iron==='cut'?'':'none';document.getElementById('lab-lining').setAttribute('fill',{red:'#ae4540',green:'#3f886d',none:'url(#wood)'}[lining]);
root.querySelectorAll('[data-iron]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.iron===iron)));root.querySelectorAll('[data-lining]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lining===lining)));
const caption=iron==='solid'?'Сплошное железо закрывает нижние слои. Даже цветная подкладка под ним не видна.':lining==='none'?'В прорезях видна тёмная основа. Форма цветка осталась, цветные просветы исчезли.':'Через те же прорези видна '+(lining==='red'?'красная':'зелёная')+' подкладка под слюдой. Железо не поменялось, а цвет узора изменился.';
document.getElementById('lab-desc').textContent=caption;document.getElementById('lab-status').textContent=caption;const done=required.every(x=>seen.has(x));document.getElementById('lab-progress').textContent='Проверено сравнений: '+seen.size+' из 4'+(done?' · Опыт завершён. +30 баллов.':'');root.querySelectorAll('[data-experiment]').forEach(e=>{e.classList.toggle('visited',seen.has(e.dataset.experiment));e.setAttribute('aria-label',(seen.has(e.dataset.experiment)?'Выполнено. ':'Не выполнено. ')+e.textContent)});try{localStorage.setItem(key,JSON.stringify({iron,lining,seen:[...seen]}))}catch{};document.dispatchEvent(new CustomEvent('material-lab-change',{detail:{complete:done}}));}
root.querySelectorAll('[data-iron]').forEach(b=>b.onclick=()=>{iron=b.dataset.iron;paint()});root.querySelectorAll('[data-lining]').forEach(b=>b.onclick=()=>{lining=b.dataset.lining;paint()});window.chestLabReset=()=>{iron='cut';lining='red';seen.clear();paint()};document.getElementById('lab-reset').onclick=window.chestLabReset;paint();})();
