const score = async p => Number(await p.locator('#headScore').innerText());
const ready = async p => p.locator('[data-route="research"]').click();
async function sort(p){for(const card of await p.locator('.sort-card').all()){const right=await card.getAttribute('data-right');await card.locator('[data-act="'+right+'"]').click()}await p.locator('#sortCheck').click()}
async function quiz(p){for(const [i,a] of [2,0,1,1,1].entries())await p.locator('#quizBox .q').nth(i).locator('.quizopt').nth(a).click()}
export const scenarios={
entry:async({page,step,check})=>{await step('Open full route',()=>ready(page));check('Fresh score',await score(page),0);await step('Answer one question',()=>page.locator('#quizBox .q').first().locator('.quizopt').nth(2).click());await page.waitForTimeout(100);await step('Reload saved answer',()=>page.reload());check('Restored earned score',await score(page),10)},
wrong:async({page,step,check})=>{await ready(page);const q=page.locator('#quizBox .q').first();await step('Choose frost-only wrong answer',()=>q.locator('.quizopt').nth(0).click());check('Wrong earns nothing',await score(page),0);check('Explanation gives both meanings',(await q.innerText()).includes('Двойной смысл'),true);await page.waitForTimeout(50);check('Answered options disabled',await q.locator('.quizopt').nth(2).isDisabled(),true);await step('Click disabled option as visitor',async()=>{const box=await q.locator('.quizopt').nth(2).boundingBox();await page.mouse.click(box.x+box.width/2,box.y+box.height/2)});await page.waitForTimeout(100);check('Locked repeat earns nothing',await score(page),0);await step('Reload locked answer',()=>page.reload());check('Wrong remains wrong after reload',await score(page),0)},
reset:async({page,step,check})=>{await ready(page);await step('Complete sorting',()=>sort(page));check('Sorting earned',await score(page),50);await step('Reset sorting',()=>page.locator('#sortReset').click());check('Reset removes sorting reward',await score(page),0);check('All cards back in pile',await page.locator('#sortPile .sort-card').count(),6);await step('Repeat sorting',()=>sort(page));check('No accumulated repeat reward',await score(page),50)},
mobile:async({page,step,check,width})=>{await ready(page);await step('Sort and quiz',async()=>{await sort(page);await quiz(page)});check('Same maximum at '+width,await score(page),100);check('No horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)},
nojs:async({page,step,check})=>{await step('Read static alternatives',()=>page.locator('.text-version').first().scrollIntoViewIfNeeded());check('Text sorting alternative',await page.locator('.text-version').count()>0,true);check('Quiz limitation explained',await page.locator('#quiz noscript p').isVisible(),true);check('Historical sheets remain',await page.locator('#act5 figure').count(),34)},
score:async({page,step,check})=>{await ready(page);await step('Earn every reward',async()=>{await sort(page);await quiz(page)});check('Maximum',await score(page),100);check('Visible denominator',(await page.locator('#quiz .resultcard').innerText()).includes('100'),true);await step('Repeat completed check',()=>page.locator('#sortCheck').click());check('No overflow',await score(page),100)},
main:async({page,step,check})=>{await ready(page);await step('Match sheets to three acts',()=>sort(page));check('All matches correct',await page.locator('.sort-card.right').count(),6);check('Main action rewarded',await score(page),50);await step('Recheck',()=>page.locator('#sortCheck').click());check('Reward not duplicated',await score(page),50)},
empty:async({page,step,check})=>{await ready(page);await step('Inspect promised collection and activities',()=>page.locator('#act5').scrollIntoViewIfNeeded());check('Alphabet has 34 sheets',await page.locator('#act5 figure').count(),34);check('Foreign title removed',await page.locator('#act5 img[src*="azbuka-cover"]').count(),0);check('Six sortable originals',await page.locator('.sort-card').count(),6);check('Five questions',await page.locator('#quizBox .q').count(),5);check('All questions have four choices',await page.locator('#quizBox .quizopt').count(),20)}
};
