def row_cells(r, links=False):
 d,t,k,why,hook,mech,proof,src,need,theme = r
 source_text = '; '.join(f'[{S[s][0]}]({S[s][1]})' if links else f'{S[s][0]}: {S[s][1]}' for s in src)
 return [f'{d:02}.02', f'{t}. [{k}] {why}', hook, mech, proof+' Источник: '+source_text]

data = [dict(zip(['day','title','date_type','date_reason','hook','mechanic','evidence','sources','preparation','theme'],r)) for r in ROWS]
(ROOT/'february.json').write_text(json.dumps({'status':'На согласование','checked_at':'2026-09-08','headers':HEADERS,'days':data,'sources':S},ensure_ascii=False,indent=2))
md = '# Музей русской этнографии — февраль\n\n'+INTRO+'\n\n'+LEGEND+'\n\n'
md += '| '+' | '.join(HEADERS)+' |\n|'+'|'.join(['---']*5)+'|\n'
for r in ROWS: md += '| '+' | '.join(row_cells(r,True))+' |\n'
md += '\n## Основа и статус\n\n'+LIMITS+'\n\nОснова: согласованная концепция v2 (решение E-05, 08.09.2026); команда Сергея собирать календарь помесячно, после утверждения января.\n'
md += '\n## Материалы для следующего этапа\n\n'
for r in ROWS:md+=f'- **{r[0]:02}.02 — {r[1]}:** {r[8]}\n'
(ROOT/'february.md').write_text(md)
with (ROOT/'february.csv').open('w',encoding='utf-8-sig',newline='') as f:
 w=csv.writer(f,delimiter=';');w.writerow(HEADERS);w.writerows(row_cells(r) for r in ROWS)

esc=html.escape
trs=''
for r in ROWS:
 d,t,k,why,hook,mech,proof,src,need,theme=r
 refs=' '.join(f'<a href="{esc(S[s][1])}" target="_blank" rel="noopener">{esc(S[s][0])} ↗</a>' for s in src)
 trs+=f'<tr id="day-{d:02}" data-type="{k}"><th scope="row">{d:02}.02</th><td><strong>{esc(t)}</strong><span class="meta">[{k}] {esc(why)}</span><span class="theme">{esc(theme)}</span></td><td class="hook">{esc(hook)}</td><td>{esc(mech)}</td><td>{esc(proof)}<div class="sources">{refs}</div><details><summary>Материалы к странице</summary><p>{esc(need)}</p></details></td></tr>'
css='''*{box-sizing:border-box}html{color:#23372f;background:#f7f4ec;font:16px/1.55 system-ui,sans-serif}body{margin:0}main{max-width:1680px;margin:auto;padding:36px 28px}header{max-width:1060px}h1{font:600 clamp(32px,4vw,56px)/1.12 Georgia,serif;margin:12px 0 20px}.eyebrow{letter-spacing:.12em;text-transform:uppercase;font-size:12px;font-weight:700;color:#886448}.lead{font-size:19px}.notice{color:#526157;font-size:14px}.toolbar{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin:24px 0}.toolbar a,button,input,select{font:inherit;border:1px solid #b9c5b9;border-radius:6px;padding:10px 14px;background:#fff;color:#23372f}a{color:#326149;text-underline-offset:3px}.toolbar a{text-decoration:none}input{min-width:240px;flex:1;max-width:420px}button{cursor:pointer}.tablewrap{overflow:auto;border:1px solid #cfd4c7;border-radius:8px;background:#fff}table{border-collapse:collapse;width:100%;min-width:1240px;table-layout:fixed}col:nth-child(1){width:5%}col:nth-child(2){width:19%}col:nth-child(3){width:21%}col:nth-child(4){width:26%}col:nth-child(5){width:29%}th,td{text-align:left;vertical-align:top;padding:18px 16px;border-bottom:1px solid #dce1d7;border-right:1px solid #e8ebe4;overflow-wrap:anywhere}thead th{background:#294c3c;color:white;font-size:14px}tbody th{white-space:nowrap;padding-left:8px;padding-right:8px;color:#294c3c;background:#f0f4eb;font-variant-numeric:tabular-nums}tr:nth-child(even) td{background:#fafbf7}.hook{font-weight:600;color:#874c2d}.meta,.theme{display:block;font-size:12px;margin-top:10px;color:#536554}.theme{color:#88725b}.sources{display:grid;gap:7px;margin-top:12px;font-size:12px}details{margin-top:12px;font-size:12px;color:#526157}summary{cursor:pointer}footer{max-width:1100px;margin-top:28px;font-size:14px;color:#526157}.count{font-weight:700}#empty{padding:24px}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #bf8853;outline-offset:3px}@media(max-width:640px){main{padding:22px 16px}.lead{font-size:17px}.toolbar>*{max-width:100%}input{width:100%;min-width:0;flex-basis:100%}.tablewrap{border-radius:4px}th,td{padding:14px 12px}}@page{size:A3 landscape;margin:12mm}@media print{html{background:white;font-size:10px;line-height:1.35}main{padding:0;max-width:none}h1{font-size:26px;margin:6px 0}.lead{font-size:11px}.notice,footer{font-size:9px}.toolbar,.scrollnote,details{display:none}.tablewrap{overflow:visible;border:0}table{min-width:0}thead{display:table-header-group}tr{break-inside:avoid}th,td{padding:8px 9px}.sources,.meta,.theme{font-size:8px;margin-top:5px}header{max-width:none}a{color:inherit}footer{break-inside:avoid}}'''
js='''const search=document.getElementById('search'),kind=document.getElementById('kind');function filter(){let n=0;document.querySelectorAll('tbody tr').forEach(r=>{const show=r.textContent.toLowerCase().includes(search.value.toLowerCase())&&(!kind.value||r.dataset.type===kind.value);r.hidden=!show;if(show)n++});document.getElementById('count').textContent=n+' из 28 дней';document.getElementById('empty').hidden=n!==0}search.addEventListener('input',filter);kind.addEventListener('change',filter);document.getElementById('reset').addEventListener('click',()=>{search.value='';kind.value='';filter()});document.getElementById('print').addEventListener('click',()=>window.print());'''
page=f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><link rel="icon" href="data:,"><title>Февраль — Музей русской этнографии</title><style>{css}</style></head><body><main><header><div class="eyebrow">Русская цивилизация · Календарь музея</div><h1>Музей русской этнографии<br>Февраль — день за днём</h1><p class="lead">{esc(INTRO)}</p><p class="notice">{esc(LEGEND)}</p></header><nav class="toolbar" aria-label="Работа с таблицей"><a href="february.xlsx" download>Скачать Excel</a><a href="february.pdf">Открыть PDF</a><a href="february.md" download>Текст таблицы</a><a href="how-it-looks.md">Как может выглядеть музей</a><button id="print">Печать</button></nav><div class="toolbar"><input id="search" type="search" aria-label="Найти день или тему" placeholder="Найти день, тему или регион"><select id="kind" aria-label="Привязка к дате"><option value="">Все дни</option><option value="К">Календарные даты</option><option value="У">Условная привязка</option></select><button id="reset">Сбросить</button><span id="count" class="count" aria-live="polite">28 из 28 дней</span></div><p class="notice scrollnote">На телефоне таблица прокручивается по горизонтали. Все пять граф сохранены.</p><div class="tablewrap" tabindex="0" role="region" aria-label="Календарь февраля"><table><colgroup>{'<col>'*5}</colgroup><thead><tr>{''.join('<th scope="col">'+esc(h)+'</th>' for h in HEADERS)}</tr></thead><tbody>{trs}</tbody></table><p id="empty" hidden>По этому запросу дней нет. Измени запрос или сбрось фильтр.</p></div><footer><p>{esc(LIMITS)}</p><p>Состав месяца ждёт согласования. Основа: концепция v2, решение E-05 от 08.09.2026. Таблица подготовлена по поручению Сергея: февраль, помесячная работа.</p></footer></main><script>{js}</script></body></html>'''
(ROOT/'index.html').write_text(page)

# XLSX средствами стандартной библиотеки: перенос строк, фильтр, закреплённая шапка.
def sheet_xml(rows,widths,height=138):
 cols=''.join(f'<col min="{i}" max="{i}" width="{w}" customWidth="1"/>' for i,w in enumerate(widths,1))
 out=[]
 for n,row in enumerate(rows,1):
  cells=[]
  for j,v in enumerate(row):
   ref=chr(65+j)+str(n)
   cells.append(f'<c r="{ref}" s="{1 if n==1 else 2}" t="inlineStr"><is><t xml:space="preserve">{escape(str(v))}</t></is></c>')
  out.append(f'<row r="{n}" ht="{30 if n==1 else height}" customHeight="1">'+''.join(cells)+'</row>')
 return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>'+cols+'</cols><sheetData>'+''.join(out)+f'</sheetData><autoFilter ref="A1:{chr(64+len(widths))}{len(rows)}"/><pageSetup orientation="landscape" paperSize="8" fitToWidth="1" fitToHeight="0"/></worksheet>'
sheets=[('Февраль',[HEADERS]+[row_cells(r) for r in ROWS],[9,40,45,64,82]),('Материалы',[['Дата','Название','Что подготовить','Статус']]+[[f'{r[0]:02}.02',r[1],r[8],'Состав — на согласование; механика — замысел'] for r in ROWS],[9,40,90,40]),('О таблице',[['Параметр','Значение'],['Статус','Проект февраля на согласование'],['Форма',INTRO],['Привязка',LEGEND],['Проверка',LIMITS],['Основа','Концепция v2, E-05 от 08.09.2026; команда собирать помесячно после января']],[25,140])]
ns='http://schemas.openxmlformats.org/package/2006/relationships'
with zipfile.ZipFile(ROOT/'february.xlsx','w',zipfile.ZIP_DEFLATED) as z:
 z.writestr('[Content_Types].xml','<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'+''.join(f'<Override PartName="/xl/worksheets/sheet{i}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>' for i in range(1,4))+'</Types>')
 z.writestr('_rels/.rels',f'<Relationships xmlns="{ns}"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>')
 z.writestr('xl/workbook.xml','<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'+''.join(f'<sheet name="{name}" sheetId="{i}" r:id="rId{i}"/>' for i,(name,*_) in enumerate(sheets,1))+'</sheets></workbook>')
 z.writestr('xl/_rels/workbook.xml.rels',f'<Relationships xmlns="{ns}">'+''.join(f'<Relationship Id="rId{i}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet{i}.xml"/>' for i in range(1,4))+'<Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>')
 z.writestr('xl/styles.xml','<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF294C3C"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>')
 for i,(_,rows,widths) in enumerate(sheets,1):z.writestr(f'xl/worksheets/sheet{i}.xml',sheet_xml(rows,widths))

assert len(ROWS)==28 and [r[0] for r in ROWS]==list(range(1,29))
assert len({r[1] for r in ROWS})==28 and all(all(str(x).strip() for x in row_cells(r)) for r in ROWS)
assert all(s in S for r in ROWS for s in r[7])
print(json.dumps({'days':28,'columns':5,'calendar_dates':sum(r[2]=='К' for r in ROWS),'conditional_dates':sum(r[2]=='У' for r in ROWS),'sources':len(S),'outputs':['index.html','february.md','february.csv','february.json','february.xlsx']},ensure_ascii=False))
