"use strict";
const details=[{"id": "cradle", "label": "Колыбель", "title": "Кроватка, которая не стоит на полу", "text": "Слева подвешена колыбель, прикрытая тканью. Проследи взглядом крепление вверх: место младенца связано с потолочной конструкцией. На общем снимке эта деталь легко теряется.", "position": "14% 45%", "scale": 2.2}, {"id": "distaff", "label": "Прялка", "title": "У этой прялки нет колеса", "text": "Справа стоит зелёная прялка с волокном. Её вертикальная часть держала кудель, а нить вытягивали и скручивали с помощью ручного веретена. Прялка и ткацкий станок выполняют разные работы.", "position": "96% 66%", "scale": 2.3}, {"id": "bed", "label": "Покрывало", "title": "Красота рядом с повседневным делом", "text": "На кровати — покрывало из разноцветных лоскутов. Приблизь узор: маленькие цветные части складываются в крупные фигуры. По фотографии можно изучить композицию; имя мастерицы и возраст вещи этот кадр не сообщает.", "position": "27% 60%", "scale": 2.5}];
const $=s=>document.querySelector(s), seen=new Set();
function show(d){$('#room').style.transformOrigin=d.position;$('#room').style.transform=`scale(${d.scale})`;$('#detail').replaceChildren();const small=document.createElement('p');small.className='eyebrow';small.textContent='Деталь / '+d.label;const h=document.createElement('h3');h.textContent=d.title;const p=document.createElement('p');p.textContent=d.text;$('#detail').append(small,h,p);seen.add(d.id);$('#seen').textContent=`Открыто ${seen.size} из ${details.length}`;document.querySelectorAll('[data-detail]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.detail===d.id)));}
document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>show(details.find(d=>d.id===b.dataset.detail)));
$('#whole').onclick=()=>{$('#room').style.transform='scale(1)';document.querySelectorAll('[data-detail]').forEach(b=>b.setAttribute('aria-pressed','false'));$('#detail').innerHTML='<p class="eyebrow">Вся комната</p><h3>Посмотри на вещи вместе</h3><p>Колыбель, покрывало и прялка снова в одном кадре. Выбери любую деталь, чтобы вернуться к ней.</p>';};
const answers={loom:'Ткацкий станок нужен на следующем этапе: из уже готовых нитей получают ткань. Но сейчас у тебя волокно. Вернись на шаг раньше.',spin:'Да. Кудель закрепляют на прялке; из неё вытягивают волокна и скручивают нить ручным веретеном. Затем из нитей можно ткать. Зелёная вещь справа на фотографии держит волокно — колеса ей не требуется.',sew:'Игла пригодится, когда появится ткань для шитья. Сейчас нужно сначала получить нить из волокна. Попробуй другую пару.'};
document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{$('#answer').textContent=answers[b.dataset.answer];$('#answer').classList.toggle('correct',b.dataset.answer==='spin');document.querySelectorAll('[data-answer]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));if(b.dataset.answer==='spin')show(details[1]);});
$('#again').onclick=()=>{$('#answer').innerHTML='<p>Выбери решение — увидишь, какой шаг оно позволяет сделать.</p>';$('#answer').classList.remove('correct');document.querySelectorAll('[data-answer]').forEach(b=>b.setAttribute('aria-pressed','false'));};
const selected=()=>[...document.querySelectorAll('.memories input:checked')].map(x=>x.value);
function memory(){const n=selected();$('#memory-result').textContent=n.length?'Ты узнал: '+n.join('; ')+'. Запиши, с кем связано это воспоминание.':'Связь с прошлым иногда начинается с одной знакомой вещи.';}
document.querySelectorAll('.memories input').forEach(c=>c.onchange=memory);
const key='rc-etno-demo-memory-v1';try{const d=JSON.parse(localStorage.getItem(key)||'null');if(d){$('#note').value=d.note||'';document.querySelectorAll('.memories input').forEach(c=>c.checked=(d.items||[]).includes(c.value));memory();}}catch{}
$('#save').onclick=()=>{try{localStorage.setItem(key,JSON.stringify({items:selected(),note:$('#note').value}));$('#saved').textContent='Сохранено на этом устройстве.';}catch{$('#saved').textContent='Браузер не разрешил сохранение. Можно скачать текст кнопкой рядом.';}};
$('#download').onclick=()=>{const text='Моё семейное воспоминание\n\n'+selected().join('\n')+'\n\n'+$('#note').value;const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='family-memory.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
$('#share').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);$('#share-status').textContent='Ссылка скопирована.';}catch{$('#share-status').textContent='Скопируй адрес из адресной строки браузера.';}};
