async(page)=>{
const checks=[],check=(name,ok,detail='')=>checks.push({name,ok,detail});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('https://arabelthera-dot.github.io/rc-museum-preview/lab/architecture-home-365/catalog.html');
await page.getByRole('button',{name:'Далее →',exact:true}).click();check('page 2',await page.locator('#catalog-count').innerText()==='13–24 из 365 · страница 2 из 31');
await page.getByRole('button',{name:'31',exact:true}).click();check('last page 5 entries',await page.locator('.catalog-entry').count()===5);check('next disabled',await page.getByRole('button',{name:'Далее →',exact:true}).isDisabled());
await page.locator('.entry-actions button').first().click();check('question dialog',await page.locator('dialog').isVisible()&&(await page.locator('#entry-hook').innerText()).length>10);await page.keyboard.press('Escape');check('escape closes',!await page.locator('dialog').isVisible());
await page.locator('#catalog-search').fill('Асташово');check('search matches',await page.locator('.catalog-entry').count()>0);await page.reload();check('reload retains query',await page.locator('#catalog-search').inputValue()==='Асташово');
await page.locator('#catalog-search').fill('незнакомыйпамятник123');check('empty',await page.locator('#catalog-empty').isVisible());await page.getByRole('button',{name:'Сбросить всё'}).click();
await page.locator('select[name=status]').selectOption('published');check('published 7',await page.locator('.catalog-entry').count()===7);
await page.locator('#clear-route').click();for(let i=0;i<3;i++)await page.locator('.story-save').nth(i).click();check('route unlock',await page.locator('#start-route').getAttribute('aria-disabled')!=='true');await page.reload();check('route persistence',await page.locator('#route-list a').count()===3);
const savedURL=page.url();await page.locator('.entry-actions a').first().click();await page.goBack({waitUntil:'commit',timeout:5000}).catch(()=>{});await page.waitForSelector('#catalog-count');check('back retains filter',page.url()===savedURL&&(await page.locator('select[name=status]').inputValue())==='published');await page.locator('#clear-route').click();
await page.getByRole('button',{name:'Сбросить всё'}).click();await page.locator('select[name=month]').selectOption('12');check('December 31',await page.locator('#catalog-count').innerText().then(x=>x.includes('из 31')));
await page.getByRole('button',{name:'Сбросить всё'}).click();await page.locator('select[name=theme]').selectOption('wood');check('theme nonempty',await page.locator('.catalog-entry').count()>0);await page.locator('select[name=region]').selectOption('Карелия');check('region matches',await page.locator('.catalog-entry').count()>0);
await page.goto('https://arabelthera-dot.github.io/rc-museum-preview/lab/architecture-home-365/index.html');
for(const view of ['space','material','people','time','place']){await page.locator('[data-view='+view+']').click();await page.waitForFunction(()=>!document.querySelector('.reader-stage').classList.contains('is-changing'));check('view '+view,await page.locator('#reader-image').evaluate(x=>x.complete&&x.naturalWidth>0));}
for(const [mode,total] of [['long',35],['short',15]]){await page.locator('[data-school='+mode+']').click();check('school '+total,await page.locator('.school-steps b').evaluateAll(xs=>xs.reduce((n,x)=>n+Number(x.textContent.match(/(\d+) мин/)[1]),0))===total)}
for(const day of [1,12,25]){await page.locator('#calbox .cday').filter({hasText:new RegExp('^'+day+'$')}).click();check('calendar '+day,(await page.locator('#calbox .calcard p').innerText()).length>5)}
await page.evaluate(()=>window.renderArchitectureToday(new Date(2026,0,1)));check('today January link',(await page.locator('#today-primary').getAttribute('href')).includes('kizhi'));await page.evaluate(()=>window.renderArchitectureToday());check('today actual',await page.locator('#today-date-label').innerText()==='5 сентября');
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.body.style.zoom='2';scrollTo(0,0)});check('zoom 200%',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),await page.evaluate(()=>({sw:document.documentElement.scrollWidth,w:innerWidth})));await page.evaluate(()=>document.body.style.zoom='');
check('console',errors.length===0,errors);return checks;
}
